name: Simple Deploy

on:
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest
    #runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3    


  deploy-dev:
    name: Deploy test
    runs-on: ubuntu-latest

    environment:
      name: test
        

    needs: build
    steps:
      - name: Test
        run: echo "Hello World"



